#ifndef MONITORING_CLIENT_H_
#define MONITORING_CLIENT_H_

#define MAX_ADDR_BUFFER_MONITORING 128
#define BUFSIZE_MONITORING 512
#define MONITORING_VERSION 1

enum {
	LIST_USERS = 1,
	ADD_USER = 2,
	REMOVE_USER = 3,
	CHANGE_PASSWORD = 4
};

#endif